### ISSUE TITLE
404 in cookie consent banner link

### ISSUE THREAD

**Issue by maximbaele** [owaspsamm/website#30] opened 2022-08-08 11:16 UTC
The "Learn More"  link in the cookie consent banner on the OWASP SAMM website leads to a 404 page at the moment.

![image](https://user-images.githubusercontent.com/8909779/183405986-c6704baf-3c6e-40c9-956d-ea2ffd26b29d.png)
![image](https://user-images.githubusercontent.com/8909779/183406021-8b3f0109-984b-4b45-a5b6-6648aa907abc.png)

**Comment by Pat-Duarte** [comment] 2022-12-21 15:51
#84 was a duplicate of this issue

**Closed** 2022-12-21 15:52 UTC
